#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/dist"
EDITION="${1:-store}"
VERSION="$(node -p "JSON.parse(require('fs').readFileSync('$ROOT/manifest.json','utf8')).version")"

case "$EDITION" in
  community)
    LABEL="community"
    ;;
  store)
    LABEL="store"
    if [[ ! -f "$ROOT/src/pro/license.js" ]]; then
      echo "package:store requires the private commercial module at src/pro/license.js" >&2
      echo "Use package:community in the public repository, or run the store build in the private release environment." >&2
      exit 1
    fi
    ;;
  *)
    echo "Usage: bash scripts/package.sh [community|store]" >&2
    exit 1
    ;;
esac

rm -rf "$OUT"
mkdir -p "$OUT/stage/src"
cp "$ROOT/manifest.json" "$OUT/stage/"
cp -R "$ROOT/src/." "$OUT/stage/src/"
cp -R "$ROOT/icons" "$OUT/stage/"
cp -R "$ROOT/_locales" "$OUT/stage/"
cp -R "$ROOT/site" "$OUT/stage/"

if [[ "$EDITION" == "community" ]]; then
  rm -rf "$OUT/stage/src/pro"
  cat > "$OUT/stage/src/edition.js" <<'EDITION_FILE'
/** Generated by scripts/package.sh. */
export const EDITION = 'community';
export const PRO_ENABLED = false;
EDITION_FILE
else
  cat > "$OUT/stage/src/edition.js" <<'EDITION_FILE'
/** Generated by scripts/package.sh. */
export const EDITION = 'store';
export const PRO_ENABLED = true;
EDITION_FILE
fi

node "$ROOT/scripts/assemble-store.mjs" "$OUT/stage" "$EDITION"

PACKAGE="$OUT/readmode-$VERSION-$LABEL.zip"
(cd "$OUT/stage" && zip -qr "$PACKAGE" .)
if [[ "$EDITION" == "community" ]] && unzip -Z1 "$PACKAGE" | grep -q '^src/pro/'; then
  echo "package:community unexpectedly contains src/pro" >&2
  exit 1
fi
LC_ALL=C shasum -a 256 "$PACKAGE" > "$PACKAGE.sha256"
rm -rf "$OUT/stage"
printf '%s\n' "$PACKAGE"
printf '%s\n' "$PACKAGE.sha256"
